services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - docker-network
    restart: always

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama_pull
    depends_on:
      - ollama
    entrypoint: >
      sh -c "sleep 5 && ollama pull llama3.2"
    environment:
      - OLLAMA_HOST=ollama:11434
    networks:
      - docker-network
    restart: "no"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data:
  file_storage: # persistent file storage for uploads and responses
