"""empty message

Revision ID: 9d57719b038b
Revises: e9656007d6d5
Create Date: 2026-03-09 23:48:32.649711

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '9d57719b038b'
down_revision: Union[str, Sequence[str], None] = 'e9656007d6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
