"""sync schema after pgvector migration

Revision ID: b58e7594559c
Revises: a1b2c3d4e5f6
Create Date: 2026-03-13 17:55:40.799256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58e7594559c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='rag_app'
    )
    op.create_index(op.f('ix_rag_app_users_email'), 'users', ['email'], unique=True, schema='rag_app')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('collection_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['rag_app.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rag_app'
    )
    op.create_index(op.f('ix_rag_app_documents_user_id'), 'documents', ['user_id'], unique=False, schema='rag_app')
    op.create_table('requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['rag_app.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rag_app'
    )
    op.create_index(op.f('ix_rag_app_requests_user_id'), 'requests', ['user_id'], unique=False, schema='rag_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_app_requests_user_id'), table_name='requests', schema='rag_app')
    op.drop_table('requests', schema='rag_app')
    op.drop_index(op.f('ix_rag_app_documents_user_id'), table_name='documents', schema='rag_app')
    op.drop_table('documents', schema='rag_app')
    op.drop_index(op.f('ix_rag_app_users_email'), table_name='users', schema='rag_app')
    op.drop_table('users', schema='rag_app')
    # ### end Alembic commands ###
