"""moved to vector db

Revision ID: ec29eee49eb2
Revises: b58e7594559c
Create Date: 2026-03-13 18:06:09.906153

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ec29eee49eb2'
down_revision: Union[str, Sequence[str], None] = 'b58e7594559c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
